#!/usr/bin/env node
/**
 * Generate syntaxes/feature.tmLanguage.json from the vendored official
 * Gherkin language data (src/gherkin/gherkin-languages.json).
 *
 * Keeps highlighting in sync with the spec — no hardcoded keyword lists.
 *
 * Usage: node scripts/generate-grammar.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';

const SRC = new URL('../src/gherkin/gherkin-languages.json', import.meta.url);
const OUT = new URL('../syntaxes/feature.tmLanguage.json', import.meta.url);

const langs = JSON.parse(await readFile(SRC, 'utf8'));

function collect(role) {
  const set = new Set();
  for (const def of Object.values(langs)) {
    for (const kw of def[role] ?? []) {
      const k = String(kw).trimEnd();
      if (k) set.add(k);
    }
  }
  return [...set].sort((a, b) => b.length - a.length);
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function alternation(keywords) {
  // Longest-first alternation; word boundary only for ASCII keywords
  return keywords.map(escapeRe).join('|');
}

const stepKeywords = [
  ...new Set([...collect('given'), ...collect('when'), ...collect('then'), ...collect('and'), ...collect('but')]),
].sort((a, b) => b.length - a.length);

function headerPattern(roles) {
  const kws = roles.flatMap(collect).sort((a, b) => b.length - a.length);
  return `^\\s*(${alternation(kws)})\\s*:`;
}

// Step keywords: CJK-style keywords may be followed directly by text;
// ASCII ones require a boundary (whitespace or end handled by lookahead).
const stepAlternation = stepKeywords.map(k =>
  /^[\x00-\x7F]+$/.test(k) ? `${escapeRe(k)}(?=\\s|$)` : escapeRe(k),
);

const grammar = {
  $comment:
    'GENERATED by scripts/generate-grammar.mjs from src/gherkin/gherkin-languages.json (cucumber/gherkin, MIT). Do not edit by hand.',
  scopeName: 'source.feature',
  patterns: [
    { include: '#language-declaration' },
    { include: '#comments' },
    { include: '#tags' },
    { include: '#feature-header' },
    { include: '#rule-header' },
    { include: '#scenario-header' },
    { include: '#background-header' },
    { include: '#examples-header' },
    { include: '#step-keyword' },
    { include: '#docstring' },
    { include: '#table' },
    { include: '#placeholder' },
    { include: '#strings' },
  ],
  repository: {
    'language-declaration': {
      match: '^\\s*#\\s*language:\\s*\\S+',
      name: 'keyword.control.language.feature',
    },
    comments: {
      match: '#.*',
      name: 'comment.line.feature',
    },
    tags: {
      match: '@[\\p{L}\\p{N}_./-]+',
      name: 'entity.name.tag.feature',
    },
    'feature-header': {
      match: headerPattern(['feature']),
      name: 'keyword.control.feature',
    },
    'rule-header': {
      match: headerPattern(['rule']),
      name: 'keyword.control.feature',
    },
    'scenario-header': {
      match: headerPattern(['scenarioOutline', 'scenario']),
      name: 'keyword.control.feature',
    },
    'background-header': {
      match: headerPattern(['background']),
      name: 'keyword.control.feature',
    },
    'examples-header': {
      match: headerPattern(['examples']),
      name: 'keyword.control.feature',
    },
    'step-keyword': {
      patterns: [
        {
          match: `^\\s*(?:${stepAlternation.join('|')})`,
          name: 'keyword.action.feature',
        },
      ],
    },
    docstring: {
      begin: '"""',
      end: '"""',
      beginCaptures: { 0: { name: 'punctuation.definition.string.begin.feature' } },
      endCaptures: { 0: { name: 'punctuation.definition.string.end.feature' } },
      name: 'string.quoted.triple.feature',
    },
    table: {
      patterns: [
        { match: '^\\s*\\|', name: 'punctuation.definition.table.feature' },
        { match: '\\|', name: 'punctuation.definition.table.feature' },
      ],
    },
    placeholder: {
      match: '<[\\p{L}\\p{N}_-]+>',
      name: 'variable.parameter.feature',
    },
    strings: {
      patterns: [
        {
          begin: '"',
          end: '"',
          beginCaptures: { 0: { name: 'punctuation.definition.string.begin.feature' } },
          endCaptures: { 0: { name: 'punctuation.definition.string.end.feature' } },
          name: 'string.quoted.double.feature',
        },
        {
          begin: "'",
          end: "'",
          beginCaptures: { 0: { name: 'punctuation.definition.string.begin.feature' } },
          endCaptures: { 0: { name: 'punctuation.definition.string.end.feature' } },
          name: 'string.quoted.single.feature',
        },
      ],
    },
  },
};

await writeFile(OUT, JSON.stringify(grammar, null, 2) + '\n');
console.log(`Generated ${OUT.pathname} (${langs.length} languages)`);
